apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: app-secret
spec:
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: my-app-secret
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: my-db-secret
        property: password
