apiVersion: policy/v1
kind: PodSecurityPolicy
metadata:
  name: restricted
spec:
  privileged: false
  runAsUser:
    rule: MustRunAsNonRoot
  volumes:
    - 'configMap'
    - 'secret'
  allowPrivilegeEscalation: false
  hostNetwork: false
